### ISSUE TITLE
where do we set Google Map API key in the code ?

### ISSUE THREAD

**Issue by sebvige** [manuel-guilbault/aurelia-talk-google-map#1]
Hello,

I am a beginner coding and I have been looking hard where to set my google map key with no luck.

Any tip ? 

Cheers

Seb

**Comment by manuel-guilbault** [comment]
Hi @sebvige,

It must be added to the URL of the google maps API:

```
http://maps.googleapis.com/maps/api/js?key=<your_key>
```

So it depends on how you load the Google Maps API. In the case of this demo app, it is in the `config.js` file:

```
System.config({
  //...
  paths: {
    // ...
    "google-maps": "http://maps.googleapis.com/maps/api/js?key=<your_key>"
  },
  //...
});
```

Hope this helps!
